name = "CubedSphere"
uuid = "7445602f-e544-4518-8976-18f8e8ae6cdb"
authors = ["ali.hh.ramadhan@gmail.com <ali.hh.ramadhan@gmail.com>"]
version = "0.1.0"

[deps]
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
