name = "CubedSphere"
uuid = "7445602f-e544-4518-8976-18f8e8ae6cdb"
authors = ["Climate Modeling Alliance and contributors"]
version = "0.3.0"

[deps]
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"

[compat]
TaylorSeries = "0.10 - 0.17"
julia = "1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Coverage", "Printf"]
